[package]
name = "hotstuff_model"
version = "0.1.0"
authors = ["Rashmi Mudduluru <rashmimudduluru@calibra.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mirai-annotations = "1.3.1"
rand = "0.3"